In [3]:
import numpy as np

In [4]:
import numpy as np
a=[2,3,4,5,6,7,8,9]
b=np.array(a)
print(b)
print(type(b))

[2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [25]:
a=[2,'6',9.5]
b=np.array(a*3)
print(b)

['2' '6' '9.5' '2' '6' '9.5' '2' '6' '9.5']


In [26]:
b=np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [16]:
a=[1,2]
b=np.ones(a,dtype=int)
print(b)

[[1 1]]


In [29]:
b=np.zeros((3,4),dtype=int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
a=[1,5]
b=np.zeros(a,dtype=int)
print(b)

[[0 0 0 0 0]]


In [30]:
b=np.full(3,5)
print(b)

[5 5 5]


In [32]:
b=np.full((3,4),5)
b

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [40]:
b=np.empty(7)
b

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 7.56599128e-307,
       1.42413555e-306, 1.78019082e-306, 4.79243676e-322])

In [48]:
import numpy as np
a=np.zeros(10,dtype=int)
a[4]=1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [50]:
a = np.arange(2,20,4)
a 

array([ 2,  6, 10, 14, 18])

In [51]:
a = np.arange(2,20)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [52]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
a=np.linspace(2,20)
a
print(a[1]-a[0])
print(a[3]-a[2])

0.36734693877551017
0.36734693877551017


In [74]:
a=np.linspace(2,20,3,dtype=int,endpoint=False) #endpoint = false i.e stop value is not included
a

array([ 2,  8, 14])

In [53]:
a=np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
a=np.eye(6,5, dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [59]:
a=np.random.rand()
a

0.9421330280006692

In [60]:
a=np.random.rand(5)
a

array([0.19211961, 0.39762079, 0.12613532, 0.31096077, 0.23067152])

In [66]:
a=np.random.randint(8)
a

4

In [4]:
import numpy as np
a=np.random.randint(2,20,5)
a

array([ 6, 15,  5,  2,  3])

### 1-D 

In [2]:
import numpy as np
li=[1,2,3,4,5]
arr=np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [5]:
print(arr.data) #location
print(arr.shape) #shape
print(arr.dtype) #type
print(arr.strides) #byte

(5,)
int32
(4,)


In [19]:
print(li[0:3])
print(arr[1:4])
print(arr[1:4][1])

[1, 2, 3]
[2 3 4]
3


### 2-D

In [11]:
import numpy as np
li_2d=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d=np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [13]:
print(arr_2d.data) #location
print(arr_2d.shape) #shape
print(arr_2d.dtype) #type
print(arr_2d.strides) #byte

(4, 4)
int32
(16, 4)


In [21]:
print(li_2d[0:3])
print(li_2d[0:3][2])
print(arr_2d[0:4])
print(arr_2d[0:3][1])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[5 6 7 8]


In [26]:
print(li_2d[0:3][2][1])
print(li_2d[2][1])
print(li_2d[1][:3])
print(arr_2d[2][1])
print(arr_2d[1][:3])

10
10
[5, 6, 7]
10
[5 6 7]


In [30]:
print(li_2d[0:3][2])
print(arr_2d[0:3,2])

[9, 10, 11, 12]
[ 3  7 11]


In [7]:
import numpy as np
li_2d=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d=np.array(li_2d)

print(arr_2d[1:3,1:3])

[[ 6  7]
 [10 11]]


### Mathematical Operations 

In [8]:
import numpy as np
a=np.random.randint(2,50,8)
b=np.random.randint(2,50,8)
c=a+b
d=a-b
e=a*b
f=a**b
g=a/b
h=a//b
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)

[10 42  6 27 15 31 38 12]
[47 22 17 31 23 19 44 35]
[57 64 23 58 38 50 82 47]
[-37  20 -11  -4  -8  12  -6 -23]
[ 470  924  102  837  345  589 1672  420]
[          0 -1438646272   193331200  1582498963   300332143  -408824225
           0           0]
[0.21276596 1.90909091 0.35294118 0.87096774 0.65217391 1.63157895
 0.86363636 0.34285714]
[0 1 0 0 0 1 0 0]


In [13]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[10 42  6 27 15 31 38 12]
181
22.625
6
2
42
1


In [16]:
print(a<b)
print(a>b)
print(a==b)

[ True False  True  True  True False  True  True]
[False  True False False False  True False False]
[False False False False False False False False]


In [18]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a,b))

[ True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True]
[0 0 0 0 0 0 0 0]


### Boolean Indexing

In [47]:
import numpy as np
a=np.array(['t','b','r','d','e','f','z','a'])
b=np.random.randint(1,20,8)
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[ 8  5 13 15  8 19 11  8]


In [48]:
print(b>10)

[False False  True  True False  True  True False]


In [49]:
bool_arr= b[b>10]
print(bool_arr)

[13 15 19 11]


In [50]:
print(b[b>10])

[13 15 19 11]


In [51]:
new_arr= b[(b>10) & (b<15)]
print(new_arr)

[13 11]


In [53]:
print(b)
c=b
c

[ 8  5 13 15  8 19 11  8]


array([ 8,  5, 13, 15,  8, 19, 11,  8])

In [75]:
#indexing of non zero elements
d=np.array([1,2,0,0,3,0])
print(np.where(d!=0))

(array([0, 1, 4], dtype=int64),)


In [79]:
#odd occurance -1
e=np.array([1,2,3,4,5,6,7,8,9,10])
odd=e[e%2!=0]=-1
e

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [91]:
#replace maximum by zero
f=np.array([23,45,6,26,77,12,8,30])
maxi=np.argmax(f)
f[maxi]=0
f

array([23, 45,  6, 26,  0, 12,  8, 30])

In [98]:
g=np.array([23,45,6,26,77,12,8,30,38,66])
idx=np.where((g>=3)&(g<=8))
g[idx]=0
g

array([23, 45,  0, 26, 77, 12,  0, 30, 38, 66])

In [3]:
import numpy as np
a=np.random.randint(1,30,(5,6))
print(a)

[[16 21 11 14  6 25]
 [ 9 22 23 28 16  1]
 [15 11 27  3 10 27]
 [ 1 16  9  8 13 15]
 [28  3 23 18 25  3]]


In [4]:
bool_arr=a>20
print(bool_arr)

[[False  True False False False  True]
 [False  True  True  True False False]
 [False False  True False False  True]
 [False False False False False False]
 [ True False  True False  True False]]


In [5]:
print(a[bool_arr])

[21 25 22 23 28 27 27 28 23 25]


In [6]:
b=a
print(a)

[[16 21 11 14  6 25]
 [ 9 22 23 28 16  1]
 [15 11 27  3 10 27]
 [ 1 16  9  8 13 15]
 [28  3 23 18 25  3]]


In [9]:
b[bool_arr]=100
print(b)

[[ 16 100  11  14   6 100]
 [  9 100 100 100  16   1]
 [ 15  11 100   3  10 100]
 [  1  16   9   8  13  15]
 [100   3 100  18 100   3]]


In [18]:
bool_arr=b[:,1]==100
print(bool_arr)

[ True  True False False False]


In [19]:
b[bool_arr,1]=99
print(b)

[[ 16  99  99  14   6 100]
 [  9  99  99 100  16   1]
 [ 15  11  99   3  10 100]
 [  1  16  99   8  13  15]
 [100   3  99  18 100   3]]


In [20]:
import numpy as np
a=np.random.randint(1,30,(5,6))
print(a)

[[ 3 23 23  1 23 12]
 [11 14  7 29  6 22]
 [12 27  5 28 15 24]
 [27 18  4 27 17 22]
 [16 19 24 13 15  3]]


In [29]:
arr=a[0:5,0]
print(arr)
sort=sorted(arr)
print(sort)

[ 3 11 12 27 16]
[3, 11, 12, 16, 27]


In [37]:
arr=a[0:5,0:6]
print(arr)
sort=arr.sort()
print(sort)

[[ 1  3 12 23 23 23]
 [ 6  7 11 14 22 29]
 [ 5 12 15 24 27 28]
 [ 4 17 18 22 27 27]
 [ 3 13 15 16 19 24]]
None


### Broadcasting

In [39]:
import numpy as np
x=np.random.randint(1,10,(2,3))
y=np.random.randint(1,10,(2,3))
print(x)
print(y)

[[6 7 2]
 [7 9 4]]
[[5 7 1]
 [1 9 3]]


In [40]:
x-y

array([[1, 0, 1],
       [6, 0, 1]])

In [45]:
import numpy as np
x=np.random.randint(1,10,(2,3))
y=np.random.randint(1,10,(3,2))
print(x)
print(y)

[[4 4 9]
 [8 5 2]]
[[1 1]
 [3 1]
 [7 7]]


In [49]:
# x-y gives error since it is of different size so,
z=np.transpose(y)
print(z)
x-z

[[1 3 7]
 [1 1 7]]


array([[ 3,  1,  2],
       [ 7,  4, -5]])

In [50]:
import numpy as np
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3))
print(x)
print(y)

[[9 4 4]
 [3 1 2]
 [3 7 8]]
[5 4 2]


In [51]:
x-y 

array([[ 4,  0,  2],
       [-2, -3,  0],
       [-2,  3,  6]])